# tack pins

# shorturl schemes
# scheme rest expands rest into {path}
[shorturls]
gh = "github:{path}"
ghtar = "https://github.com/{path}/archive/refs/heads/main.zip"
ghtar-master = "https://github.com/{path}/archive/refs/heads/master.zip"
catppuccin = "https://github.com/catppuccin/{path}/archive/refs/heads/main.zip"

# all_follow maps input names to the top-level pin they follow
# opt out per-input with exclude_follow
[all_follow]
nixpkgs = "nixpkgs"

# Flakes

[inputs.nixpkgs]
url = "gh:NixOS/nixpkgs?ref=nixos-unstable"

[inputs.hjem]
url = "gh:feel-co/hjem"

[inputs.helium]
url = "gh:AlvaroParker/helium-nix"

# tars / zips

[inputs.catppuccin-obs]
url = "catppuccin:obs" # 07.09.26
type = "fixed"

[inputs.catppuccin-prismlauncher]
url = "catppuccin:prismlauncher" # 07.09.26
type = "fixed"

[inputs.catppuccin-fish]
url = "catppuccin:fish" # 07.09.26
type = "fixed"

[inputs.nixos-hardware]
url = "ghtar-master:NixOS/nixos-hardware" # 07.09.26
type = "fixed"

[inputs.tuxedo]
url = "ghtar:webstonehq/tuxedo" # 07.09.26
type = "fixed"

[inputs.yazi-flavors]
url = "ghtar:yazi-rs/flavors" # 07.09.26
type = "fixed"
