# tack pins

# shorturl schemes
# scheme rest expands rest into {path}
[shorturls]
gh = "github:{path}"
catppuccin = "github:catppuccin/{path}"

# all_follow maps input names to the top-level pin they follow
# opt out per-input with exclude_follow
[all_follow]
nixpkgs = "nixpkgs"

# Flake-like inputs

[inputs.nixpkgs]
url = "gh:NixOS/nixpkgs?ref=nixos-unstable"

[inputs.hjem]
url = "gh:feel-co/hjem"

[inputs.helium]
url = "gh:AlvaroParker/helium-nix"

[inputs.millennium]
url = "gh:SteamClientHomebrew/Millennium"
dir = "packages/nix"

[inputs.duck-game-rebuilt]
url = "github:klof44/DuckGameRebuilt-Nix"

# tars / zips - more akin to npins

[inputs.catppuccin-obs]
url = "catppuccin:obs"
type = "fetch"

[inputs.catppuccin-fish]
url = "catppuccin:fish"
type = "fetch"

[inputs.nixos-hardware]
url = "gh:NixOS/nixos-hardware"
type = "fetch"

[inputs.tuxedo]
url = "gh:webstonehq/tuxedo"
type = "fetch"

[inputs.yazi-flavors]
url = "gh:yazi-rs/flavors"
type = "fetch"
