theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
continue-comments = false
bufferline = "multiple"
popup-border = "all"
end-of-line-diagnostics = "info"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false  # show hidden files

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[keys.normal]
# Select name + value, hopefully
"'" = "@ghvglmmx"
# Select to end of line
"ret" = "@vgl"

[keys.normal.l]
y = [
  ":sh rm -f /tmp/unique-file",
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ":open %sh{cat /tmp/unique-file}",
  ":redraw",
]
g = [
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
]
